version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=front
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE=server
    volumes:
      - .:/app
    ports:
      - "3000:3000"
