name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      json-server:
        image: clue/json-server
        ports:
          - 3001:3000
        options: >-
          --network=host
        env:
          JSON_SERVER_PORT: 3000
        volumes:
          - ./db-e2e.json:/data/db.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # ou a versão que você estiver usando

      - name: Install dependencies
        run: pnpm install

      - name: Start dev server
        run: |
          # Inicie o servidor em segundo plano
          pnpm dev &

      - name: Wait for dev server to be ready
        run: |
          # Aguarde até que o servidor esteja disponível
          npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: pnpm playwright:e2e
